mklink /H  .\2h\test.cpp   .\1h\test.cpp
mklink /H  .\2h\test.h   .\1h\test.h
mklink /H  .\2h\myconstant.cpp   .\1h\myconstant.cpp
mklink /H  .\2h\myconstant.h   .\1h\myconstant.h
mklink /H  .\2h\mystr.c   .\1h\mystr.c
mklink /H  .\2h\mystr.h   .\1h\mystr.h
mklink /H  .\2h\mytcp.cpp  .\1h\mytcp.cpp
mklink /H  .\2h\mytcp.h   .\1h\mytcp.h
mklink /H  .\2h\mytimer.c   .\1h\mytimer.c
mklink /H  .\2h\mytimer.h   .\1h\mytimer.h
mklink /H  .\2h\myudp.cpp   .\1h\myudp.cpp
mklink /H  .\2h\myudp.h   .\1h\myudp.h
mklink /H  .\2h\mywarn.cpp   .\1h\mywarn.cpp
mklink /H  .\2h\mywarn.h   .\1h\mywarn.h
mklink /H  .\2h\mywifi.cpp   .\1h\mywifi.cpp
mklink /H  .\2h\mywifi.h   .\1h\mywifi.h
mklink /H  .\2h\savevalues.cpp   .\1h\savevalues.cpp
mklink /H  .\2h\savevalues.h   .\1h\savevalues.h

